apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs
spec:
  replicas: 1  # Number of replicas (pods) to run
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs-app
          image: guser1/nodejs:v1  # Replace with your Docker Hub image
          ports:
            - containerPort: 3005  # Port your Node.js app listens on
